
trigger:
- none

pool:
  name: Terraform Agent
  demands:
   - agent.name -equals Terraform-Agent

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:  
        
          - task: TerraformInstaller@1
            displayName: Terraform install
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTaskV4@4
            displayName: Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure-Connect'
              backendAzureRmResourceGroupName: 'Terraform-RG'
              backendAzureRmStorageAccountName: 'terraformbackend23091998'
              backendAzureRmContainerName: 'terraform-state'
              backendAzureRmKey: 'terraform.tfstate'
              
          - task: TerraformTaskV4@4
            displayName: Validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
  
  - stage: tfdeploy
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: apply
        steps: 
           - task: TerraformInstaller@1
             displayName: Terraform install
             inputs:
              terraformVersion: 'latest'
            
           - task: TerraformTaskV4@4
             displayName: Init
             inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure-Connect'
              backendAzureRmResourceGroupName: 'Terraform-RG'
              backendAzureRmStorageAccountName: 'terraformbackend23091998'
              backendAzureRmContainerName: 'terraform-state'
              backendAzureRmKey: 'terraform.tfstate'

           - task: TerraformTaskV4@4
             displayName: Plan
             inputs:
               provider: 'azurerm'
               command: 'plan'
               environmentServiceNameAzureRM: 'Azure-Connect'
               commandOptions: '-input=false'

           - task: TerraformTaskV4@4
             displayName: Apply
             inputs:
               provider: 'azurerm'
               command: 'apply'
               environmentServiceNameAzureRM: 'Azure-Connect'
